#!/usr/bin/env bash
set -euo pipefail

BUNDLE_DIR="${1:-REVIEW_BUNDLE}"

mkdir -p "$BUNDLE_DIR"

write_or_placeholder() {
  local target="$1"
  local content="$2"
  printf "%s\n" "$content" >"$target"
}

changed_files() {
  if command -v git >/dev/null 2>&1 && git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    git diff --name-only HEAD
  else
    printf "git-unavailable\n"
  fi
}

write_or_placeholder "$BUNDLE_DIR/SUMMARY.md" "# Review Summary

- Generated by scripts/review/generate_review_bundle.sh
- Update this summary with project-specific risk notes before merge."

changed_files >"$BUNDLE_DIR/FILE_MANIFEST.txt"

write_or_placeholder "$BUNDLE_DIR/RISK_REPORT.md" "# Risk Report

- Review auth, network, filesystem, subprocess, and dependency changes."

write_or_placeholder "$BUNDLE_DIR/DEPENDENCY_DIFF.md" "# Dependency Diff

- Record lockfile and package manifest changes here."

write_or_placeholder "$BUNDLE_DIR/DOCKER_REPORT.md" "# Docker Report

- Record base image, user, ports, volumes, and capability changes here."

write_or_placeholder "$BUNDLE_DIR/TEST_EVIDENCE.md" "# Test Evidence

- Record executed commands and their outcomes here."

write_or_placeholder "$BUNDLE_DIR/DECISION_TRACE.md" "# Decision Trace

- Map changed files to decision IDs from docs/DECISION_LOG.md."

write_or_placeholder "$BUNDLE_DIR/POLICY_CHECKLIST.md" "# Policy Checklist

- [ ] Review bundle generated for this PR
- [ ] No secrets in source, history, or config
- [ ] New dependencies reviewed (license + risk)
- [ ] Docker changes reviewed (base image, user, ports, caps)
- [ ] High-risk APIs reviewed (subprocess, eval/exec, network egress, crypto)
- [ ] Every non-trivial change maps to a decision entry with explicit rationale
- [ ] Human approval count meets policy"

printf "Generated review bundle in %s\n" "$BUNDLE_DIR"
